import User from "./user";
import Search from "./Search";
import Home from "./Home";
import Video from "./Video";
import Watch from "./Watch";
import C from "./C";
import Menu from "./Menu";
import Notification from "./Notification";
import Messenger from "./Messenger";
import Logo from "./Logo";
import Friends from "./Friends";
import Groups from "./Groups";
import Pages from "./Pages";
import Saved from "./Saved";
import More from "./More";
import Gallery from "./Gallery";
import Create from "./Create";
import Camera from "./Camera";
import Plus from "./Plus";
import Cross from "./Cross";
import Like from "./Like";
import Comment from "./Comment";
import Share from "./Share";
import DotsMenu from "./DotsMenu";
import Pause from "./Pause";
import Events from "./Events";
import Favourites from "./Favourites";
import Memories from "./Memories";
import Settings from "./Settings";
import MenuBtn from './MenuBtn';
import PlusCircle from "./PlusCircle";
import Send from "./Send";
import PostColors from "./PostColors";
import TagFriend from "./TagFriend";
import CircleCross from "./CircleCross";
import FaceEmoji from './FaceEmoji'
import FaceEmojiFill from './FaceEmojiFill'
import Gif from "./Gif";
import Location from './Location';
import Save from "./Save";
import Online from "./Online";
import VideoFill from "./VideoFill";
import RightArrow from "./RightArrow";
import LocationFillSquare from "./LocationFillSquare";
import Private from "./Private";
import EyeFill from "./EyeFill";
import HeartOutline from "./HeartOutline";
import DoubleTick from "./DoubleTick";
import RightArrowPrimary from "./RightArrowPrimary";
import SendRequest from "./SendRequest";
import Birthday from "./Birthday";
import AddImage from "./AddImage";
import SettingsCircle from "./SettingsCircle";
import HelpSupportCircle from "./HelpSupportCircle";
import FeedbackCircle from "./FeedbackCircle";
import LogoutCircle from "./LogoutCircle";
import MessengerCircle from "./MessengerCircle";
import ReportCircle from "./ReportCircle";
import NewsFeed from "./NewsFeed";
import Story from "./Story";
import SingleUser from "./SingleUser";
import Public from "./Public";
import LeftArrow from "./LeftArrow";
import Public2 from "./Public2";
import LikePrimary from "./LikePrimary";
import Security from "./Security";
import StoryBook from "./StoryBook";
import Location2 from "./Location2";
import Block from "./Block";
import Clips from "./Clips";
import PlusPrimary from "./PlusPrimary";
import Edit from './Edit'
import HelpSupport from "./HelpSupport";
import Feedback from "./Feedback";
import Logout from "./Logout";

export { 
    User , Search , Home , Video , Watch , C , Menu , Notification , Messenger , Logo , Friends , Groups , Pages , Saved , More , Gallery , Create , Camera , Plus , Cross , Like , Comment , Share , DotsMenu , Pause , Events , Favourites ,
    Memories , Settings , MenuBtn , PlusCircle , Send , PostColors , TagFriend , CircleCross , FaceEmoji , FaceEmojiFill , Gif , Location , Save , Online , VideoFill , RightArrow , LocationFillSquare , Private , EyeFill , HeartOutline , DoubleTick ,  RightArrowPrimary , SendRequest , Birthday , AddImage , SettingsCircle , HelpSupportCircle , FeedbackCircle , LogoutCircle , MessengerCircle , ReportCircle , NewsFeed , Story , SingleUser , Public , LeftArrow , Public2 , LikePrimary , Security , StoryBook , Block , Location2 , Clips , PlusPrimary , Edit , HelpSupport , Logout , Feedback
} 
